"""create cases and evidence_records

Revision ID: 3007c4397bd8
Revises: 
Create Date: 2026-09-25 00:28:19.622332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3007c4397bd8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('dispute_type', sa.Enum('ROUTE_DEVIATION', 'CLEANING_FEE', 'SAFETY_ALERT', 'NO_SHOW_CHARGE', name='disputetype', native_enum=False), nullable=False),
    sa.Column('current_state', sa.Enum('INIT_CLAIM', 'ROUND_1_PLEADINGS', 'ROUND_2_PROSECUTOR_AUDIT', 'JUDGE_DELIBERATION', 'EXECUTION_ROUTER', name='casestate', native_enum=False), nullable=False),
    sa.Column('current_round', sa.Integer(), nullable=False),
    sa.Column('resolution_channel', sa.Enum('FULLY_AUTOMATED', 'ESCALATED_HUMAN_REVIEW', name='resolutionchannel', native_enum=False), nullable=True),
    sa.Column('trip_id', sa.String(length=64), nullable=True),
    sa.Column('rider_id', sa.String(length=64), nullable=False),
    sa.Column('driver_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_index(op.f('ix_cases_driver_id'), 'cases', ['driver_id'], unique=False)
    op.create_index(op.f('ix_cases_rider_id'), 'cases', ['rider_id'], unique=False)
    op.create_table('evidence_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('evidence_id', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.Enum('GPS_TELEMETRY', 'CHAT_LOG', 'RECEIPT', 'ROUTE_TRAJECTORY', 'PAYMENT_RECORD', 'IMAGE', 'EXIF_METADATA', 'HISTORICAL_PROFILE', 'APP_EVENT', 'OTHER', name='evidencesourcetype', native_enum=False), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_records_case_id'), 'evidence_records', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_records_case_id'), table_name='evidence_records')
    op.drop_table('evidence_records')
    op.drop_index(op.f('ix_cases_rider_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_driver_id'), table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
