/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Complete data contracts, state context objects, and structured outputs for the Ryde dispute resolution pipeline. Designed for JSON Schema draft 2020-12 with strict type validation, explicit required properties, and seamless conversion to Python Pydantic models and TypeScript interfaces.
 */
export interface RydeMultiAgentAutonomousDisputeResolutionSystemMasterSchema {
  case_metadata: CaseMetadata;
  data_sources: DataSources;
  round_1_statements: Round1Statements;
  round_2_cross_exam: Round2CrossExam;
  round_3_rebuttal: Round3Rebuttal;
  bonus_modules: BonusModules;
  prosecutor_findings: ProsecutorReport;
  judge_verdict: JudgeVerdict;
}
/**
 * Top-level case identification and workflow state-control object.
 */
export interface CaseMetadata {
  /**
   * Unique identifier for the dispute case (e.g., RYDE-DSP-20260322001).
   */
  case_id: string;
  /**
   * Category of the dispute, determining the evidence-collection and policy-evaluation path.
   */
  dispute_type: "ROUTE_DEVIATION" | "CLEANING_FEE" | "SAFETY_ALERT";
  /**
   * Current state in the dispute resolution state machine.
   */
  current_state:
    | "INIT_CLAIM"
    | "ROUND_1_PLEADINGS"
    | "ROUND_2_PROSECUTOR_AUDIT"
    | "ROUND_3_CONDITIONAL_REBUTTAL"
    | "JUDGE_DELIBERATION"
    | "EXECUTION_ROUTER";
  /**
   * The active round number in the multi-round conversation protocol.
   */
  current_round: 1 | 2 | 3;
  /**
   * Whether the Dynamic Stopping Engine determined that Round 3 conditional rebuttal is warranted. False if no new substantial evidence was introduced in Round 2 responses.
   */
  is_round3_triggered: boolean;
  /**
   * The execution path determined by the EXECUTION_ROUTER gate. FULLY_AUTOMATED for confidence >= 0.75 with no safety/fraud flags; ESCALATED_HUMAN_REVIEW otherwise.
   */
  resolution_channel: "FULLY_AUTOMATED" | "ESCALATED_HUMAN_REVIEW";
  /**
   * Reference to the original Ryde trip that generated this dispute.
   */
  trip_id?: string;
  /**
   * Unique identifier for the passenger involved in the dispute.
   */
  rider_id?: string;
  /**
   * Unique identifier for the driver involved in the dispute.
   */
  driver_id?: string;
  /**
   * ISO 8601 timestamp of case creation.
   */
  created_at: string;
  /**
   * ISO 8601 timestamp of the last state transition.
   */
  updated_at: string;
}
/**
 * Container for all collected telemetry, communication, payment, and historical data sources.
 */
export interface DataSources {
  gps_telemetry: GPSAndTelemetry;
  chat_communication: ChatAndCommunication;
  payment_fare_data: PaymentAndFareData;
  /**
   * Historical profiles for all parties involved.
   *
   * @minItems 1
   */
  historical_profiles: [HistoricalProfile, ...HistoricalProfile[]];
}
/**
 * GPS and telemetry data comparing actual vs. optimal route, deviations, and stops.
 */
export interface GPSAndTelemetry {
  /**
   * Ordered GPS coordinates representing the actual driven route.
   *
   * @minItems 2
   */
  actual_route: [GPSCoordinate, GPSCoordinate, ...GPSCoordinate[]];
  /**
   * Ordered GPS coordinates representing the optimal/planned route.
   *
   * @minItems 2
   */
  optimal_route: [GPSCoordinate, GPSCoordinate, ...GPSCoordinate[]];
  /**
   * Total off-route deviation distance in kilometers.
   */
  deviation_distance_km: number;
  /**
   * Array of detected unexpected stationary stops.
   *
   * @minItems 0
   */
  unexpected_stops: UnexpectedStop[];
  /**
   * Total actual trip duration in seconds.
   */
  trip_duration_seconds: number;
  /**
   * Estimated optimal trip duration in seconds for comparison.
   */
  optimal_duration_seconds?: number;
  /**
   * Maximum recorded speed during the trip.
   */
  max_speed_kmh?: number;
  /**
   * Average speed during the trip.
   */
  average_speed_kmh?: number;
}
/**
 * A single GPS coordinate point with timestamp.
 */
export interface GPSCoordinate {
  /**
   * Latitude in decimal degrees.
   */
  latitude: number;
  /**
   * Longitude in decimal degrees.
   */
  longitude: number;
  /**
   * ISO 8601 timestamp of this GPS ping.
   */
  timestamp: string;
  /**
   * Vehicle speed at this point in km/h.
   */
  speed_kmh?: number;
  /**
   * Heading direction in degrees (0-360).
   */
  heading_degrees?: number;
}
/**
 * A detected unexpected stationary stop during the trip.
 */
export interface UnexpectedStop {
  location: GPSCoordinate;
  /**
   * When the stop began.
   */
  start_time: string;
  /**
   * Duration of the stationary stop in seconds.
   */
  duration_seconds: number;
  /**
   * Whether this stop is flagged as a route deviation or suspicious activity.
   */
  deviation_flagged: boolean;
  /**
   * Driver's or system's explanation for the stop, if available.
   */
  explanation_provided?: string;
}
/**
 * In-app chat transcript, sentiment analysis, and safety threat detection.
 */
export interface ChatAndCommunication {
  /**
   * Ordered chat message transcript.
   *
   * @minItems 0
   */
  transcript: ChatMessage[];
  /**
   * Aggregate sentiment score for the entire conversation, -1.0 to 1.0.
   */
  overall_sentiment_score: number;
  /**
   * Whether any safety-threatening keywords were detected across the transcript.
   */
  safety_threat_keywords_detected: boolean;
  /**
   * IDs of messages flagged for safety concerns.
   */
  flagged_messages?: string[];
}
/**
 * A single message in the in-app chat transcript between rider and driver.
 */
export interface ChatMessage {
  /**
   * Unique identifier for the chat message.
   */
  message_id: string;
  /**
   * Who sent the message.
   */
  sender: "RIDER" | "DRIVER" | "SYSTEM";
  /**
   * Full text content of the chat message.
   */
  content: string;
  /**
   * ISO 8601 timestamp of the message.
   */
  timestamp: string;
  /**
   * Sentiment analysis score from -1.0 (negative) to 1.0 (positive).
   */
  sentiment_score?: number;
  /**
   * Safety-threatening keywords detected in this message (e.g., 'weapon', 'assault', 'police').
   */
  safety_threat_keywords?: string[];
}
/**
 * Payment and fare data including original breakdown, disputed amount, and promo details.
 */
export interface PaymentAndFareData {
  original_fare: FareBreakdown;
  /**
   * The monetary amount in dispute.
   */
  disputed_amount: number;
  /**
   * ISO 4217 currency code for the disputed amount.
   */
  disputed_amount_currency: string;
  /**
   * Any amount already refunded to the rider before dispute resolution.
   */
  amount_already_refunded?: number;
  /**
   * Payment method used (e.g., 'credit_card', 'grabpay', 'cash').
   */
  payment_method?: string;
  /**
   * Reference to the original payment transaction.
   */
  transaction_reference?: string;
}
/**
 * Itemized fare breakdown for the trip.
 */
export interface FareBreakdown {
  /**
   * Base fare amount.
   */
  base_fare: number;
  /**
   * Distance-based fare component.
   */
  distance_fare: number;
  /**
   * Time-based fare component.
   */
  time_fare: number;
  /**
   * Surge pricing multiplier applied (e.g., 1.5 for 1.5x).
   */
  surge_multiplier?: number;
  /**
   * Promo or discount code applied, if any.
   */
  promo_code?: string;
  /**
   * Discount amount from promo code.
   */
  promo_discount?: number;
  /**
   * Final total fare charged.
   */
  total_fare: number;
  /**
   * ISO 4217 currency code.
   */
  currency: string;
}
/**
 * Historical risk and behavioral profile for a single party (rider or driver).
 */
export interface HistoricalProfile {
  /**
   * The party this profile belongs to.
   */
  party: "RIDER" | "DRIVER";
  /**
   * Historical risk score from 0.0 (low risk) to 1.0 (high risk).
   */
  risk_score: number;
  /**
   * Number of disputes filed by or against this party in the last 30 days.
   */
  dispute_history_30d: number;
  /**
   * Number of disputes filed by or against this party in the last 90 days.
   */
  dispute_history_90d: number;
  /**
   * Average user rating (1-5 scale).
   */
  rating_average?: number;
  /**
   * Whether the rating pattern shows anomalies (e.g., sudden drop, suspicious clustering).
   */
  rating_pattern_anomaly?: boolean;
  /**
   * Whether this party has been flagged for bad-faith behavior in prior cases.
   */
  bad_faith_flag: boolean;
  /**
   * Reason for bad-faith flag, if applicable.
   */
  bad_faith_reason?: string;
}
/**
 * Initial pleading objects submitted by Rider Advocate and Driver Advocate agents during ROUND_1_PLEADINGS.
 */
export interface Round1Statements {
  rider_statement: AgentStatement;
  driver_statement: AgentStatement;
}
/**
 * Structured statement submitted by an Advocate Agent (Rider or Driver) in any round of the multi-round protocol.
 */
export interface AgentStatement {
  /**
   * The party this statement represents.
   */
  party: "RIDER" | "DRIVER";
  /**
   * The agent role that produced this statement.
   */
  agent_role: "RIDER_ADVOCATE" | "DRIVER_ADVOCATE" | "PROSECUTOR" | "JUDGE";
  /**
   * Concise natural-language summary of the party's argument or claim.
   */
  argument_summary: string;
  /**
   * Extended argument text with full reasoning, citations, and narrative.
   */
  detailed_argument?: string;
  /**
   * The outcome the party is requesting (e.g., 'full_refund', 'cleaning_fee_charge', 'case_dismissed').
   */
  requested_outcome:
    "FULL_REFUND" | "PARTIAL_REFUND" | "CLEANING_FEE_CHARGE" | "NO_PENALTY" | "CASE_DISMISSED" | "OTHER";
  /**
   * Monetary amount requested by this party, in the trip's currency.
   */
  requested_amount: number;
  /**
   * ISO 4217 currency code for the requested amount.
   */
  currency?: string;
  /**
   * List of evidence source identifiers cited in support of the argument.
   *
   * @minItems 0
   */
  evidence_references: EvidenceReference[];
  /**
   * ISO 8601 timestamp of statement submission.
   */
  submitted_at: string;
}
/**
 * A reference to a specific piece of evidence within the collected data sources.
 */
export interface EvidenceReference {
  /**
   * Unique identifier for the evidence item (e.g., 'GPS-001', 'CHAT-003', 'IMG-002').
   */
  evidence_id: string;
  /**
   * The category of evidence source.
   */
  source_type:
    | "GPS_TELEMETRY"
    | "CHAT_LOG"
    | "RECEIPT"
    | "ROUTE_TRAJECTORY"
    | "PAYMENT_RECORD"
    | "IMAGE"
    | "EXIF_METADATA"
    | "HISTORICAL_PROFILE"
    | "OTHER";
  /**
   * Human-readable summary of what this evidence demonstrates.
   */
  description: string;
}
/**
 * Container for the Prosecutor's targeted questions and the Advocates' responses during ROUND_2_PROSECUTOR_AUDIT.
 */
export interface Round2CrossExam {
  /**
   * Questions generated by the Prosecutor Agent, directed to specific parties.
   *
   * @minItems 0
   */
  targeted_questions: TargetedQuestion[];
  /**
   * Advocate responses addressing each targeted question.
   *
   * @minItems 0
   */
  targeted_responses: TargetedResponse[];
  /**
   * Whether Round 2 cross-examination has been completed.
   */
  round2_completed: boolean;
  /**
   * ISO 8601 timestamp of Round 2 completion.
   */
  completed_at?: string;
}
/**
 * A question generated by the Prosecutor Agent and directed to a specific party during ROUND_2_PROSECUTOR_AUDIT cross-examination.
 */
export interface TargetedQuestion {
  /**
   * Unique identifier for the targeted question (e.g., 'Q-001').
   */
  question_id: string;
  /**
   * The party to whom the question is directed.
   */
  directed_to: "RIDER" | "DRIVER" | "BOTH";
  /**
   * The full text of the targeted question (e.g., 'Driver, please explain the 4-minute stationary stop at GPS point X').
   */
  question_text: string;
  /**
   * Reference to the evidence that prompted this question (e.g., 'GPS-001: unexpected stop at 14:32').
   */
  evidence_context: string;
  /**
   * The evidentiary category the question probes.
   */
  category:
    | "GPS_DEVIATION"
    | "TIME_WINDOW"
    | "CHAT_CONTENT"
    | "RECEIPT_VALIDITY"
    | "ROUTE_TRAJECTORY"
    | "IMAGE_AUTHENTICITY"
    | "HISTORICAL_PATTERN"
    | "MISSING_EVIDENCE"
    | "OTHER";
  /**
   * ISO 8601 timestamp when the question was issued.
   */
  asked_at: string;
}
/**
 * An Advocate Agent's response to a specific targeted question from the Prosecutor.
 */
export interface TargetedResponse {
  /**
   * Unique identifier for the response (e.g., 'R-001').
   */
  response_id: string;
  /**
   * The ID of the targeted question this response addresses.
   */
  question_id: string;
  /**
   * The party providing the response.
   */
  responding_party: "RIDER" | "DRIVER";
  /**
   * The full text of the party's response to the targeted question.
   */
  response_text: string;
  /**
   * Whether this response introduces new evidence not previously submitted. This flag feeds the Dynamic Stopping Engine for Round 3 triggering.
   */
  introduced_new_evidence: boolean;
  /**
   * Evidence references introduced in this response, if any.
   */
  new_evidence_references: EvidenceReference[];
  /**
   * ISO 8601 timestamp of the response.
   */
  responded_at: string;
}
/**
 * Conditional rebuttal objects for ROUND_3_CONDITIONAL_REBUTTAL. Triggered ONLY if Round 2 responses introduced new evidence that substantially alters the claims.
 */
export interface Round3Rebuttal {
  /**
   * Whether Round 3 was triggered by the Dynamic Stopping Engine. If false, cross-examination stopped to prevent truth-evasion by debate skills.
   */
  is_triggered: boolean;
  /**
   * Whether new evidence was provided during Round 2 responses that warranted a Round 3 rebuttal.
   */
  new_evidence_provided: boolean;
  /**
   * Whether the new evidence caused a substantive change in the claims that requires rebuttal.
   */
  substantive_claim_change: boolean;
  /**
   * If Round 3 was NOT triggered, explanation of why the Dynamic Stopping Engine halted (e.g., 'No new substantial evidence introduced; further debate risks truth-evasion').
   */
  stopping_engine_reason?: string;
  /**
   * Rebuttal statements from each party, if Round 3 was triggered.
   *
   * @minItems 0
   */
  rebuttals: AgentStatement[];
  /**
   * ISO 8601 timestamp of Round 3 completion.
   */
  completed_at?: string;
}
/**
 * Container for bonus and verification modules: multimodal image/EXIF analysis, fraud assessment, and escalation protocol.
 */
export interface BonusModules {
  /**
   * Array of image and EXIF analysis results for submitted evidence images.
   *
   * @minItems 0
   */
  image_exif_analyses: ExifAnalysis[];
  fraud_assessment: FraudAssessment;
  escalation_protocol: EscalationProtocol;
}
/**
 * EXIF metadata and AI-generated image detection analysis for multimodal evidence (primarily Cleaning Fee disputes).
 */
export interface ExifAnalysis {
  /**
   * Unique identifier for the submitted image (e.g., 'IMG-001').
   */
  image_id: string;
  /**
   * URL or path to the submitted image.
   */
  image_url: string;
  /**
   * EXIF-embedded timestamp of when the photo was taken.
   */
  exif_timestamp: string;
  exif_gps_location: GPSCoordinate;
  /**
   * Whether the image is detected as AI-generated (synthetic/fabricated).
   */
  is_ai_generated: boolean;
  /**
   * Confidence score (0.0-1.0) for the AI-generated detection result.
   */
  ai_generated_confidence: number;
  /**
   * Classification of the stain or damage type detected in the image.
   */
  stain_damage_classification:
    "LIQUID_SPILL" | "VOMIT" | "FOOD_RESIDUE" | "PHYSICAL_DAMAGE" | "DIRT_MUD" | "NO_DAMAGE_DETECTED" | "OTHER";
  /**
   * Estimated severity of the detected damage.
   */
  damage_severity?: "MINOR" | "MODERATE" | "SEVERE";
  /**
   * Whether the EXIF timestamp and GPS location are consistent with the trip's time and route.
   */
  exif_consistent_with_trip?: boolean;
  /**
   * Whether this image has been detected as a recycled/reused image from a prior case (fraud indicator).
   */
  recycled_image_detected?: boolean;
  /**
   * If recycled image detected, the case_id of the prior case where this image was used.
   */
  recycled_image_match_case_id?: string;
}
/**
 * Fraud and bad-faith detection agent output, including risk score, risk factors, and collusion flags.
 */
export interface FraudAssessment {
  /**
   * Overall fraud risk score from 0.0 (no risk) to 1.0 (high risk).
   */
  fraud_risk_score: number;
  /**
   * List of identified fraud risk factors (e.g., 'Recycled photo detected', 'EXIF timestamp mismatch', 'Collusion pattern with driver').
   *
   * @minItems 0
   */
  risk_factors: string[];
  /**
   * Whether collusion between rider and driver is suspected.
   */
  collusion_warning_flag: boolean;
  /**
   * Description of collusion evidence, if the flag is set.
   */
  collusion_evidence?: string;
  /**
   * Whether an abuse pattern (e.g., repeated fake claims) is detected.
   */
  abuse_pattern_detected: boolean;
  /**
   * Description of the detected abuse pattern.
   */
  abuse_pattern_description?: string;
  /**
   * Recommended action based on fraud assessment.
   */
  recommended_fraud_action?: "NO_ACTION" | "FLAG_FOR_REVIEW" | "BLOCK_ACCOUNT" | "REFER_TO_FRAUD_TEAM";
}
/**
 * Escalation protocol and safety net configuration for routing cases to human review.
 */
export interface EscalationProtocol {
  /**
   * Whether a safety threat was detected (violence keywords, physical dispute indicators).
   */
  safety_threat_detected: boolean;
  /**
   * Categorical fraud risk level.
   */
  fraud_risk_level: "LOW" | "MEDIUM" | "HIGH";
  /**
   * Array of human-readable reasons for escalation (e.g., 'Low confidence 0.62', 'Possible physical dispute mentioned in chat', 'Recycled photo detected').
   *
   * @minItems 0
   */
  escalation_reasons: string[];
  /**
   * Whether this case is escalated to human review.
   */
  is_escalated: boolean;
  /**
   * Priority level assigned for human review queue routing.
   */
  priority_level: "STANDARD" | "HIGH_PRIORITY" | "URGENT";
  /**
   * The confidence score threshold below which escalation is triggered.
   */
  escalation_threshold_confidence?: number;
  /**
   * Whether crucial evidence is missing, triggering escalation.
   */
  missing_crucial_evidence?: boolean;
}
/**
 * Prosecutor Agent's final audit report submitted to the Judge Agent, containing verified facts, disputed facts, and missing facts.
 */
export interface ProsecutorReport {
  /**
   * Array of immutable, evidence-backed verified facts established during cross-examination.
   *
   * @minItems 0
   */
  verified_facts: Fact[];
  /**
   * Array of unverified claims that remain contested between parties.
   *
   * @minItems 0
   */
  disputed_facts: Fact[];
  /**
   * Array of critical evidence that is missing and could not be established during cross-examination.
   *
   * @minItems 0
   */
  missing_facts: Fact[];
  /**
   * Prosecutor's overall summary of the audit findings and case posture.
   */
  prosecutor_summary?: string;
  /**
   * ISO 8601 timestamp of report submission to the Judge Agent.
   */
  report_submitted_at: string;
}
/**
 * A single fact item within the Prosecutor's audit report ΓÇö verified, disputed, or missing.
 */
export interface Fact {
  /**
   * Unique identifier for the fact (e.g., 'F-VER-001', 'F-DIS-001', 'F-MIS-001').
   */
  fact_id: string;
  /**
   * Natural-language description of the fact.
   */
  description: string;
  /**
   * Evidence references that support or relate to this fact.
   *
   * @minItems 0
   */
  supporting_evidence: EvidenceReference[];
  /**
   * Which party this fact is most relevant to.
   */
  party_relevance?: "RIDER" | "DRIVER" | "BOTH" | "NEUTRAL";
  /**
   * Reference to the relevant Ryde policy clause, if applicable (e.g., 'Ryde-Policy-4.2.1: Route Deviation').
   */
  policy_clause_reference?: string;
  /**
   * Confidence level for this specific fact (0.0-1.0). Applicable to verified and disputed facts.
   */
  confidence_level?: number;
}
/**
 * Judge Agent's final verdict including ruling, confidence, reasoning, recommended action, dual explanations, and execution payload.
 */
export interface JudgeVerdict {
  /**
   * The ruling outcome determined by the Judge Agent.
   */
  ruling_type: "APPROVED" | "PARTIAL_REFUND" | "REJECTED" | "ESCALATED";
  /**
   * Confidence score (0.0 to 1.0) for the ruling. Scores >= 0.75 qualify for FULLY_AUTOMATED execution if no safety/fraud flags are raised.
   */
  confidence_score: number;
  /**
   * Natural language explanation of the ruling, mapped to verified facts and policy clauses.
   */
  reasoning_summary: string;
  /**
   * IDs of verified facts from the Prosecutor report that the ruling is based on.
   *
   * @minItems 0
   */
  verified_fact_references?: string[];
  /**
   * Policy clause references applied in reaching the ruling.
   *
   * @minItems 0
   */
  policy_clauses_applied?: string[];
  /**
   * References to prior similar cases used as precedent.
   *
   * @minItems 0
   */
  precedent_references?: string[];
  recommended_action: RecommendedAction;
  /**
   * Dual natural language summaries tailored to each party.
   */
  explanations: {
    /**
     * Plain-language explanation of the ruling addressed to the rider.
     */
    explanation_for_rider: string;
    /**
     * Plain-language explanation of the ruling addressed to the driver.
     */
    explanation_for_driver: string;
  };
  execution_payload: ExecutionPayload;
  /**
   * ISO 8601 timestamp of the Judge's deliberation.
   */
  deliberated_at: string;
}
/**
 * Exact financial action recommended by the Judge Agent.
 */
export interface RecommendedAction {
  /**
   * The type of financial action to execute.
   */
  action_type:
    "FULL_REFUND" | "PARTIAL_REFUND" | "CLEANING_FEE_CHARGE" | "NO_REFUND" | "PENALTY_ONLY" | "ESCALATED_NO_ACTION";
  /**
   * Exact refund amount to be issued to the rider, if applicable. 0 if no refund.
   */
  refund_amount: number;
  /**
   * Cleaning fee to be charged to the rider, if applicable. 0 if not applicable.
   */
  cleaning_fee_amount?: number;
  /**
   * ISO 4217 currency code.
   */
  currency: string;
  /**
   * Penalty points assigned to the at-fault party's account (driver or rider).
   */
  penalty_points?: number;
  /**
   * Which party receives the penalty points.
   */
  penalty_target?: "RIDER" | "DRIVER" | "NONE";
  /**
   * Additional account-level action recommendation.
   */
  account_action?: "NONE" | "WARNING_ISSUED" | "TEMPORARY_SUSPENSION" | "ACCOUNT_BAN";
}
/**
 * Execution output containing the autonomous or human-in-the-loop execution status and details.
 */
export interface ExecutionPayload {
  /**
   * The execution outcome status. AUTO_EXECUTED for fully automated resolution; PENDING_HUMAN_APPROVAL for escalated cases.
   */
  execution_status: "AUTO_EXECUTED" | "PENDING_HUMAN_APPROVAL" | "HUMAN_CONFIRMED" | "HUMAN_OVERRIDDEN";
  /**
   * Mock API reference / transaction ID generated upon auto-execution. Populated only when execution_status is AUTO_EXECUTED.
   */
  transaction_id?: string;
  /**
   * ISO 8601 timestamp of automated execution. Populated only when execution_status is AUTO_EXECUTED.
   */
  auto_executed_at?: string;
  /**
   * Final archival status of the case.
   */
  case_final_status?: "AUTO_RESOLVED" | "HUMAN_RESOLVED" | "HUMAN_OVERRIDDEN" | "PENDING";
  human_confirmation_details?: HumanConfirmationDetails;
  /**
   * ISO 8601 timestamp of case resolution or escalation.
   */
  resolved_at: string;
}
/**
 * Details of human operator review and confirmation. Populated ONLY when the case is escalated to human review.
 */
export interface HumanConfirmationDetails {
  /**
   * Unique identifier of the human operator who reviewed the case.
   */
  reviewer_id?: string;
  /**
   * Display name of the human reviewer.
   */
  reviewer_name?: string;
  /**
   * ISO 8601 timestamp of human approval/override.
   */
  approval_timestamp?: string;
  /**
   * The human operator's decision.
   */
  approval_decision?: "CONFIRMED_AUTO" | "MODIFIED" | "OVERRIDDEN" | "REJECTED_AUTO";
  /**
   * Reason provided by the human operator if they modified or overrode the auto-recommendation.
   */
  override_reason?: string;
  modified_action?: RecommendedAction;
  /**
   * Rich summary card content presented to the human operator for 1-click confirmation.
   */
  human_summary_card?: string;
}
